<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <a style="font-size: 18px" class="navbar-brand" href="/admin"><i class="fa-solid fa-tooth fa-fade"></i>Dental Clinic</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    </div>
</nav>